return PlaceObj('ModDef', {
	'title', "5xSun - AutoRefill",
	'description', "5xSun - AutoRefill automatically scans and replenishes your resource deposits 5 times a sol (at hours 0, 5, 10, 15, and 20).\n\nBy default, it refills surface and subsurface deposits (Concrete, Metals, Rare Metals, Water, and Rare Minerals) to their maximum capacity when they drop below 30%, ensuring a steady and reliable supply for your colony.\n\nFeatures:\n\nFully supports all realms (Surface, Subsurface, and Asteroids).\nCustomizable via in-game Mod Options: adjust the refill threshold percentage or toggle specific resources on and off.\nIncludes non-intrusive on-screen notifications summarizing which deposits were refilled in each cycle.",
	'short_description', "Automatically scans and refills resource deposits (Concrete, Metals, Rare Metals, Water, Rare Minerals) 5 times a sol when they drop below a customizable threshold (default 30%).",
	'image', "Mod/iaTFkGp/Screenshots/1.png",
	'last_changes', "it finally works",
	'id', "iaTFkGp",
	'author', "Speedle",
	'version', 32,
	'lua_revision', 350453,
	'saved_with_revision', 396349,
	'optional_mod', true,
	'code', {
		"Code/5xSun_Init.lua",
		"Code/5xSun_Panels.lua",
	},
	'default_options', {
		FIVESUNlowPercent = 30,
		SurfaceDepositConcrete = true,
		SurfaceDepositMetals = true,
		SurfaceDepositPreciousMetals = true,
		SurfaceDepositPreciousMinerals = true,
		SurfaceDepositWater = true,
	},
	'saved', 1783104515,
	'code_hash', -6227790139598654362,
	'screenshot1', "Mod/iaTFkGp/Screenshots/1.png",
	'screenshot2', "Mod/iaTFkGp/Screenshots/2.png",
	'pdx_id', 149893,
	'pdx_version', "1",
	'steam_id', "3756959772",
	'TagGameplay', true,
	'TagInterface', true,
	'TagTools', true,
})